//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTNTHAM_2210900124_PRJ.Views.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaodichTK
    {
        public int GiaodichID { get; set; }
        public Nullable<decimal> Sotien { get; set; }
        public Nullable<System.DateTime> Ngaygiaodich { get; set; }
        public string Mota { get; set; }
        public Nullable<int> ThanhVienID { get; set; }
    
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
