//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTNTHAM_2210900124_PRJ.Views.Shared
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project1_2210900124DTNTEntities : DbContext
    {
        public Project1_2210900124DTNTEntities()
            : base("name=Project1_2210900124DTNTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GiaodichTK> GiaodichTK { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<NguoiHoTro> NguoiHoTro { get; set; }
        public virtual DbSet<QUANTRI> QUANTRI { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ThanhVien> ThanhVien { get; set; }
    }
}
