//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTNTHAM_2210900124_PRJ.Views.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiHoTro
    {
        public int NguoiHoTroID { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public string LinhVucHoTro { get; set; }
        public Nullable<int> QuanTriID { get; set; }
    
        public virtual QUANTRI QUANTRI { get; set; }
    }
}
